#!/usr/bin/env python3
"""Bundle the plutopy source for the Pyodide-based web playground.

Reads everything under src/plutopy/ and emits docs/playground/files.js
as a JS map that the playground writes into Pyodide's MEMFS at boot.

Run this manually (or via the docs CI workflow) any time the package
source changes:

    python scripts/build_playground.py
"""
from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "plutopy"
OUT = ROOT / "docs" / "playground" / "files.js"


def main() -> int:
    if not SRC.is_dir():
        print(f"plutopy source not found at {SRC}", file=sys.stderr)
        return 1
    OUT.parent.mkdir(parents=True, exist_ok=True)
    files: dict[str, str] = {}
    for path in sorted(SRC.rglob("*")):
        if not path.is_file():
            continue
        if path.suffix in {".pyc"} or "__pycache__" in path.parts:
            continue
        rel = "plutopy/" + path.relative_to(SRC).as_posix()
        files[rel] = path.read_text()
    OUT.write_text(
        "// Auto-generated by scripts/build_playground.py. Do not edit by hand.\n"
        "window.PLUTOPY_FILES = " + json.dumps(files, indent=2) + ";\n"
    )
    print(f"wrote {OUT} with {len(files)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
